### PR TITLE
Network request now looks like a table

### PR DESCRIPTION
**Pull request by kmisha**
I suppose that network tool should looks like a table. So, I made a few changes for styles.

**Demo landscape**
demo_landscape

**Demo portrait**
demo_portait

### CODE REVIEW

**Comment by surunzi** [comment]
It looks better, but harder to checkout infos such as url. I'll try to see if there's a better way for requests view later. Thanks for pr.

**Comment by kmisha** [comment]
> 
> 
> It looks better, but harder to checkout infos such as url. I'll try to see if there's a better way for requests view later. Thanks for pr.

May I open an issue for that?

**Comment by surunzi** [comment]
@kmisha Yes, you can create one.

**Comment by surunzi** [comment]
It's optimized in v1.8.0.

**Pull request closed without merging**
