### PR TITLE
Added Amoled theme (pls add this theme)

### PR DESCRIPTION
**Pull request by T3M1N4L**
I have curated a custom theme for eruda, that many individuals like me have always wanted. An AMOLED theme!

Owners - if you are seeing this, please do accept this one.

### CODE REVIEW

**Comment by T3M1N4L** [comment]
pls do tell me if I should change any other files :)

**Comment by Dhyfer1** [comment]
Hey, how can I create a custom theme?

**Comment by T3M1N4L** [comment]
> Hey, how can I create a custom theme?

You can add themes by editing the themes.js file

specifically these parts:

```JS

const darkThemes = [
  'Dark',
  'Material Oceanic',
  'Material Darker',
  'Material Palenight',
  'Material Deep Ocean',
  'Monokai Pro',
  'Dracula',
  'Arc Dark',
  'Atom One Dark',
  'Solarized Dark',
  'Night Owl',
  'AMOLED',
]
```

I added (AMOLED) which is a different theme

at the end add your own code with the same name, then simply edit the colors

(Stuff under AMOLED is my own code)
```JS
  'Light Owl': createLightTheme([
    '#FAFAFA', '#546e7a', '#403f53', '#269386', '#E0E7EA',
    '#efefef', '#403F53', '#FAFAFA', '#0C969B', '#c96765',
    '#994cc3', '#aa0982', '#7d818b', '#994cc3', '#546e7a',
    '#994cc3', '#4876d6', '#4876d6', '#637777',
  ]),
  'AMOLED': createDarkTheme([
    '#000000', '#8F93A2', '#FFFFFF', '#68FFAE', '#000000',
   '#41465b', '#4B526D', '#000000', '#DEFDF7', '#38ff9f',
    '#ab2eff', '#A76DF7', '#38ff9f', '#86F3C7', '#8F93A2',
    '#ab2eff', '#8293FF', '#38ff9f', '#6575c7',
  ]),
}
```

**Comment by Dhyfer1** [comment]
Ok, I understand. Look, I'm not an advanced user but I want to create a theme, and I understood what you said before but how do I test the custom theme after editing the file you mention?

**Comment by T3M1N4L** [comment]
Honestly, you might have to build the whole thing yourself locally then test it, building instructions should be in the readme. All I did was base AMOLED off an already existing theme, while using the color picker extensions. 😅

**Comment by Dhyfer1** [comment]
> Honestly, you might have to build the whole thing yourself locally then test it, building instructions should be in the readme.

As I said before, I have no idea how to do it, I'm not a programmer, I don't know anything about code. The easy part is to edit the xml file to include a new theme, only that could do it, but I don't know anything to know how to build eruda 😕

**Comment by T3M1N4L** [comment]
> As I said before, I have no idea how to do it, I'm not a programmer, I don't know anything about code. The easy part is to edit the js file to include a new theme, only that could do it, but I don't know anything to know how to build eruda 😕

I don't know how to help you just check the readme on how to build it locally, and build it and if you find any issues just search it up on google. Or just create a pull request and edit the colors in your new theme then get it accepted then see if your colors were correct or something

**Comment by Dhyfer1** [comment]
Wait a minute let me see if I understand. So you created a new theme by editing the .js file adding some colors with the help of an extension to know the hex value, but you didn't build the repo to test your theme before submitting this commit? 

If so, then how did you check that each color was in the correct place without building the repo? How did you test your theme before this commit?

Because I thought it was necessary to build the repo to test a new theme, or am I wrong? 

Lastly, what is the link to build Eruda? Is the last link in the Readme that says 'Contributing guide'?

**Comment by T3M1N4L** [comment]
Ok so basically, I loaded eruda in a new tabe at https://eruda.liriliri.io/ then I used a color picker extension to see the colors of an existing theme, then I changed the colors

https://chromewebstore.google.com/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg?pli=1

**Comment by Dhyfer1** [comment]
> Ok so basically, I loaded eruda in a new tabe at https://eruda.liriliri.io/ then I used a color picker extension to see the colors of an existing theme, then I changed the colors

That's it? you didn't have to build anything?

**Comment by T3M1N4L** [comment]
Nope, I didn't build anything,

**Comment by Dhyfer1** [comment]
> Nope, I didn't build anything, 

It was what I wanted to know. Well, you said before that you opened Eruda in a new tab and used an extension, but with that alone you don't know how the colors are looking good. So I assume you took a screenshot before of the parts where you were going to apply the custom color, and edit the screenshot with the custom colors to see how they look

**Comment by T3M1N4L** [comment]
I used the extension to find the hex values of a specific color in an existing theme and I replaced that color with my color of choice in the file.

**Pull request merged**
